spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect